# Generated by Django 4.2.3 on 2023-08-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_contact_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='phoneno',
        ),
    ]
