# Generated by Django 4.2.3 on 2023-08-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_phonenumber_contact_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneno',
            new_name='phonenumber',
        ),
    ]
