# Generated by Django 4.2.3 on 2023-08-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
