# Generated by Django 4.2.3 on 2023-08-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
