# Generated by Django 4.2.3 on 2023-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_blogs_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='link',
        ),
        migrations.AddField(
            model_name='blogs',
            name='links',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
