# Generated by Django 4.2.3 on 2023-08-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_contact_description_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
